use super::traits::{ApplyResult, PreviewResult, TemplateFile, TemplateFiles, ToolAdapter};
use crate::error::Result;
use std::fs;
use std::path::{Path, PathBuf};

/// GitHub Copilot adapter
///
/// Converts templates to GitHub Copilot format:
/// - rules/*.md → .github/copilot-instructions.md (merged)
/// - memory/*.md → .github/copilot-instructions.md (appended)
/// - commands/*.md → .github/prompts/*.prompt.md
/// - agents/*.md → .github/agents/*.agent.md
/// - skills/*.ts → .github/skills/ or .claude/skills/ (shared)
/// - mcp/*.json → .vscode/mcp.json
pub struct CopilotAdapter {
    project_dir: PathBuf,
}

impl CopilotAdapter {
    pub fn new(project_dir: &Path) -> Self {
        Self {
            project_dir: project_dir.to_path_buf(),
        }
    }

    /// Get the .github directory path
    fn github_dir(&self) -> PathBuf {
        self.project_dir.join(".github")
    }

    /// Get the .vscode directory path
    fn vscode_dir(&self) -> PathBuf {
        self.project_dir.join(".vscode")
    }

    /// Get the copilot-instructions.md file path
    fn copilot_instructions_file(&self) -> PathBuf {
        self.github_dir().join("copilot-instructions.md")
    }

    /// Ensure .github directory exists
    fn ensure_github_dir(&self) -> Result<()> {
        let github_dir = self.github_dir();
        if !github_dir.exists() {
            fs::create_dir_all(&github_dir)?;
        }
        Ok(())
    }

    /// Ensure .vscode directory exists
    fn ensure_vscode_dir(&self) -> Result<()> {
        let vscode_dir = self.vscode_dir();
        if !vscode_dir.exists() {
            fs::create_dir_all(&vscode_dir)?;
        }
        Ok(())
    }

    /// Apply rules files: rules/*.md → .github/copilot-instructions.md (merged)
    fn apply_rules(&self, files: &[TemplateFile], result: &mut ApplyResult) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let instructions_file = self.copilot_instructions_file();

        // Merge all rules files into copilot-instructions.md
        let mut content = String::new();

        // Add header
        content.push_str("# GitHub Copilot Instructions\n\n");
        content.push_str("<!-- Generated by aidot - DO NOT EDIT MANUALLY -->\n\n");

        for (i, file) in files.iter().enumerate() {
            if i > 0 {
                content.push_str("\n\n---\n\n");
            }
            content.push_str(&format!("## {}\n\n", file.relative_path.replace("rules/", "").replace(".md", "")));
            content.push_str(&file.content);
        }

        let action = if instructions_file.exists() {
            "updated"
        } else {
            "created"
        };

        fs::write(&instructions_file, content)?;

        if action == "created" {
            result.add_created(".github/copilot-instructions.md".to_string());
        } else {
            result.add_updated(".github/copilot-instructions.md".to_string());
        }

        Ok(())
    }

    /// Apply memory files: memory/*.md → .github/copilot-instructions.md (appended)
    fn apply_memory(&self, files: &[TemplateFile], result: &mut ApplyResult) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let instructions_file = self.copilot_instructions_file();

        // Read existing content or start fresh
        let mut content = if instructions_file.exists() {
            fs::read_to_string(&instructions_file)?
        } else {
            String::from("# GitHub Copilot Instructions\n\n<!-- Generated by aidot -->\n")
        };

        // Append memory content
        content.push_str("\n\n---\n\n## Project Context\n\n");

        for (i, file) in files.iter().enumerate() {
            if i > 0 {
                content.push_str("\n\n---\n\n");
            }
            content.push_str(&format!("### {}\n\n", file.relative_path.replace("memory/", "").replace(".md", "")));
            content.push_str(&file.content);
        }

        fs::write(&instructions_file, content)?;
        result.add_updated(".github/copilot-instructions.md".to_string());

        Ok(())
    }

    /// Apply commands: commands/*.md → .github/prompts/*.prompt.md
    fn apply_commands(&self, files: &[TemplateFile], result: &mut ApplyResult) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let prompts_dir = self.github_dir().join("prompts");
        fs::create_dir_all(&prompts_dir)?;

        for file in files {
            // Convert filename: command-name.md → command-name.prompt.md
            let original_name = file.relative_path.replace("commands/", "");
            let prompt_name = if original_name.ends_with(".md") {
                original_name.replace(".md", ".prompt.md")
            } else {
                format!("{}.prompt.md", original_name)
            };

            let target_path = prompts_dir.join(&prompt_name);
            fs::write(&target_path, &file.content)?;
            result.add_created(format!(".github/prompts/{}", prompt_name));
        }

        Ok(())
    }

    /// Apply MCP configs: mcp/*.json → .vscode/mcp.json
    fn apply_mcp(&self, files: &[TemplateFile], result: &mut ApplyResult) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        self.ensure_vscode_dir()?;
        let mcp_file = self.vscode_dir().join("mcp.json");

        // Read existing mcp.json or create new with Copilot structure
        let mut mcp_config: serde_json::Value = if mcp_file.exists() {
            let content = fs::read_to_string(&mcp_file)?;
            serde_json::from_str(&content)?
        } else {
            // Copilot uses "servers" instead of "mcpServers"
            serde_json::json!({
                "inputs": [],
                "servers": {}
            })
        };

        // Ensure servers object exists
        if mcp_config.get("servers").is_none() {
            mcp_config["servers"] = serde_json::json!({});
        }

        // Merge MCP configurations
        for file in files {
            let server_config: serde_json::Value = serde_json::from_str(&file.content)?;
            let server_name = file.relative_path
                .replace("mcp/", "")
                .replace(".json", "");

            mcp_config["servers"][server_name] = server_config;
        }

        let json_str = serde_json::to_string_pretty(&mcp_config)?;
        fs::write(&mcp_file, json_str)?;

        result.add_updated(".vscode/mcp.json".to_string());

        Ok(())
    }

    /// Apply agents: agents/*.md → .github/agents/*.agent.md
    fn apply_agents(&self, files: &[TemplateFile], result: &mut ApplyResult) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let agents_dir = self.github_dir().join("agents");
        fs::create_dir_all(&agents_dir)?;

        for file in files {
            // Convert filename: agent-name.md → agent-name.agent.md
            let original_name = file.relative_path.replace("agents/", "");
            let agent_name = if original_name.ends_with(".md") {
                original_name.replace(".md", ".agent.md")
            } else {
                format!("{}.agent.md", original_name)
            };

            let target_path = agents_dir.join(&agent_name);
            fs::write(&target_path, &file.content)?;
            result.add_created(format!(".github/agents/{}", agent_name));
        }

        Ok(())
    }

    /// Apply skills: skills/*.ts → .github/skills/
    fn apply_skills(&self, files: &[TemplateFile], result: &mut ApplyResult) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let skills_dir = self.github_dir().join("skills");
        fs::create_dir_all(&skills_dir)?;

        for file in files {
            let filename = file.relative_path.replace("skills/", "");
            let target_path = skills_dir.join(&filename);

            fs::write(&target_path, &file.content)?;
            result.add_created(format!(".github/skills/{}", filename));
        }

        Ok(())
    }
}

impl ToolAdapter for CopilotAdapter {
    fn name(&self) -> &str {
        "GitHub Copilot"
    }

    fn detect(&self) -> bool {
        // Check if .github/copilot-instructions.md exists
        if self.copilot_instructions_file().exists() {
            return true;
        }

        // Check if .github/instructions/ directory exists
        let instructions_dir = self.github_dir().join("instructions");
        if instructions_dir.exists() {
            return true;
        }

        // Check if .github directory exists (likely a GitHub project)
        if self.github_dir().exists() {
            return true;
        }

        // Check if .vscode directory exists (VS Code project, might use Copilot)
        if self.vscode_dir().exists() {
            return true;
        }

        false
    }

    fn apply(
        &self,
        template_files: &TemplateFiles,
        _target_dir: &Path,
        _force: bool,
    ) -> Result<ApplyResult> {
        self.ensure_github_dir()?;

        let mut result = ApplyResult::new();

        // Apply each section
        self.apply_rules(&template_files.rules, &mut result)?;
        self.apply_memory(&template_files.memory, &mut result)?;
        self.apply_commands(&template_files.commands, &mut result)?;
        self.apply_mcp(&template_files.mcp, &mut result)?;
        self.apply_agents(&template_files.agents, &mut result)?;
        self.apply_skills(&template_files.skills, &mut result)?;
        // Note: hooks and settings are not directly applicable to Copilot

        Ok(result)
    }

    fn preview(
        &self,
        template_files: &TemplateFiles,
        _target_dir: &Path,
    ) -> PreviewResult {
        let mut result = PreviewResult::new();
        let instructions_file = self.copilot_instructions_file();
        let mcp_file = self.vscode_dir().join("mcp.json");

        // Rules → .github/copilot-instructions.md
        if !template_files.rules.is_empty() {
            if instructions_file.exists() {
                result.add_would_update(".github/copilot-instructions.md".to_string(), "rules".to_string());
            } else {
                result.add_would_create(".github/copilot-instructions.md".to_string(), "rules".to_string());
            }
        }

        // Memory → .github/copilot-instructions.md (appended)
        if !template_files.memory.is_empty() {
            result.add_would_update(".github/copilot-instructions.md".to_string(), "memory".to_string());
        }

        // Commands → .github/prompts/*.prompt.md
        for file in &template_files.commands {
            let original_name = file.relative_path.replace("commands/", "");
            let prompt_name = if original_name.ends_with(".md") {
                original_name.replace(".md", ".prompt.md")
            } else {
                format!("{}.prompt.md", original_name)
            };
            let target = format!(".github/prompts/{}", prompt_name);
            let target_path = self.github_dir().join("prompts").join(&prompt_name);
            if target_path.exists() {
                result.add_would_update(target, "commands".to_string());
            } else {
                result.add_would_create(target, "commands".to_string());
            }
        }

        // MCP → .vscode/mcp.json
        if !template_files.mcp.is_empty() {
            if mcp_file.exists() {
                result.add_would_update(".vscode/mcp.json".to_string(), "mcp".to_string());
            } else {
                result.add_would_create(".vscode/mcp.json".to_string(), "mcp".to_string());
            }
        }

        // Agents → .github/agents/*.agent.md
        for file in &template_files.agents {
            let original_name = file.relative_path.replace("agents/", "");
            let agent_name = if original_name.ends_with(".md") {
                original_name.replace(".md", ".agent.md")
            } else {
                format!("{}.agent.md", original_name)
            };
            let target = format!(".github/agents/{}", agent_name);
            let target_path = self.github_dir().join("agents").join(&agent_name);
            if target_path.exists() {
                result.add_would_update(target, "agents".to_string());
            } else {
                result.add_would_create(target, "agents".to_string());
            }
        }

        // Skills → .github/skills/
        for file in &template_files.skills {
            let filename = file.relative_path.replace("skills/", "");
            let target = format!(".github/skills/{}", filename);
            let target_path = self.github_dir().join("skills").join(&filename);
            if target_path.exists() {
                result.add_would_update(target, "skills".to_string());
            } else {
                result.add_would_create(target, "skills".to_string());
            }
        }

        result
    }
}
