use super::traits::{
    write_with_conflict, ApplyResult, ConflictMode, PresetFile, PresetFiles, ScanResult,
    ToolAdapter,
};
use crate::error::Result;
use std::fs;
use std::path::{Path, PathBuf};

/// Cursor adapter
///
/// Converts presets to Cursor format:
/// - rules/*.md → .cursorrules (merged into single file)
/// - memory/*.md → .cursorrules (appended)
/// - commands/*.md → .cursor/commands/
/// - mcp/*.json → .cursor/mcp.json (mcpServers section)
/// - hooks/*.json → .cursor/hooks.json
/// - agents/*.md → .cursor/agents/
/// - skills/*.ts → .cursor/skills/
pub struct CursorAdapter {
    project_dir: PathBuf,
}

impl CursorAdapter {
    pub fn new(project_dir: &Path) -> Self {
        Self {
            project_dir: project_dir.to_path_buf(),
        }
    }

    /// Get the .cursor directory path
    fn cursor_dir(&self) -> PathBuf {
        self.project_dir.join(".cursor")
    }

    /// Get the .cursorrules file path
    fn cursorrules_file(&self) -> PathBuf {
        self.project_dir.join(".cursorrules")
    }

    /// Ensure .cursor directory exists
    fn ensure_cursor_dir(&self) -> Result<()> {
        let cursor_dir = self.cursor_dir();
        if !cursor_dir.exists() {
            fs::create_dir_all(&cursor_dir)?;
        }
        Ok(())
    }

    /// Apply rules files: rules/*.md → .cursorrules
    fn apply_rules(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let cursorrules = self.cursorrules_file();

        // Build preset content
        let mut preset_content = String::new();
        preset_content.push_str("# Cursor Rules\n");
        preset_content.push_str("# Generated by aidot\n\n");

        for (i, file) in files.iter().enumerate() {
            if i > 0 {
                preset_content.push_str("\n\n---\n\n");
            }
            preset_content.push_str(&format!("# Source: {}\n\n", file.relative_path));
            preset_content.push_str(&file.content);
        }

        *mode = write_with_conflict(&cursorrules, &preset_content, *mode, result, ".cursorrules")?;

        Ok(())
    }

    /// Apply memory files: memory/*.md → .cursorrules (appended)
    fn apply_memory(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let cursorrules = self.cursorrules_file();

        // Build memory content
        let mut memory_content = String::from("\n\n---\n\n# Project Memory\n\n");
        for (i, file) in files.iter().enumerate() {
            if i > 0 {
                memory_content.push_str("\n\n---\n\n");
            }
            memory_content.push_str(&format!(
                "## {}\n\n",
                file.relative_path.replace("memory/", "").replace(".md", "")
            ));
            memory_content.push_str(&file.content);
        }

        // Read existing content or create header
        let base = if cursorrules.exists() {
            fs::read_to_string(&cursorrules)?
        } else {
            String::from("# Cursor Rules\n# Generated by aidot\n")
        };
        let content = format!("{}{}", base, memory_content);

        *mode = write_with_conflict(&cursorrules, &content, *mode, result, ".cursorrules")?;

        Ok(())
    }

    /// Apply commands: commands/*.md → .cursor/commands/
    fn apply_commands(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let commands_dir = self.cursor_dir().join("commands");
        fs::create_dir_all(&commands_dir)?;

        for file in files {
            let filename = file.relative_path.replace("commands/", "");
            let target_path = commands_dir.join(&filename);
            let display_path = format!(".cursor/commands/{}", filename);

            *mode = write_with_conflict(&target_path, &file.content, *mode, result, &display_path)?;
        }

        Ok(())
    }

    /// Apply MCP configs: mcp/*.json → .cursor/mcp.json (mcpServers section)
    fn apply_mcp(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let mcp_file = self.cursor_dir().join("mcp.json");

        // Read existing or create new
        let mut mcp_config: serde_json::Value = if mcp_file.exists() {
            let content = fs::read_to_string(&mcp_file)?;
            serde_json::from_str(&content)?
        } else {
            serde_json::json!({})
        };

        // Ensure mcpServers object exists
        if mcp_config.get("mcpServers").is_none() {
            mcp_config["mcpServers"] = serde_json::json!({});
        }

        // Merge MCP configurations
        for file in files {
            let server_config: serde_json::Value = serde_json::from_str(&file.content)?;
            let server_name = file.relative_path.replace("mcp/", "").replace(".json", "");
            mcp_config["mcpServers"][server_name] = server_config;
        }

        let json_str = serde_json::to_string_pretty(&mcp_config)?;
        *mode = write_with_conflict(&mcp_file, &json_str, *mode, result, ".cursor/mcp.json")?;

        Ok(())
    }

    /// Apply hooks: hooks/*.json → .cursor/hooks.json
    fn apply_hooks(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let hooks_file = self.cursor_dir().join("hooks.json");

        // Merge all hooks into one JSON object with standard structure
        let mut hooks_config = serde_json::json!({
            "version": 1,
            "hooks": {}
        });

        for file in files {
            let hook_config: serde_json::Value = serde_json::from_str(&file.content)?;
            let hook_name = file
                .relative_path
                .replace("hooks/", "")
                .replace(".json", "");

            // Add to hooks object
            if let Some(hooks_obj) = hooks_config.get_mut("hooks") {
                hooks_obj[hook_name] = hook_config;
            }
        }

        let json_str = serde_json::to_string_pretty(&hooks_config)?;
        *mode = write_with_conflict(&hooks_file, &json_str, *mode, result, ".cursor/hooks.json")?;

        Ok(())
    }

    /// Apply agents: agents/*.md → .cursor/agents/
    fn apply_agents(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let agents_dir = self.cursor_dir().join("agents");
        fs::create_dir_all(&agents_dir)?;

        for file in files {
            let filename = file.relative_path.replace("agents/", "");
            let target_path = agents_dir.join(&filename);
            let display_path = format!(".cursor/agents/{}", filename);

            *mode = write_with_conflict(&target_path, &file.content, *mode, result, &display_path)?;
        }

        Ok(())
    }

    /// Apply skills: skills/*.ts → .cursor/skills/
    fn apply_skills(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let skills_dir = self.cursor_dir().join("skills");
        fs::create_dir_all(&skills_dir)?;

        for file in files {
            let filename = file.relative_path.replace("skills/", "");
            let target_path = skills_dir.join(&filename);
            let display_path = format!(".cursor/skills/{}", filename);

            *mode = write_with_conflict(&target_path, &file.content, *mode, result, &display_path)?;
        }

        Ok(())
    }
}

impl ToolAdapter for CursorAdapter {
    fn name(&self) -> &str {
        "Cursor"
    }

    fn detect(&self) -> bool {
        // Check if .cursorrules file exists
        if self.cursorrules_file().exists() {
            return true;
        }

        // Check if .cursor directory exists
        if self.cursor_dir().exists() {
            return true;
        }

        // Check if cursor command exists
        #[cfg(target_os = "windows")]
        let check_cmd = std::process::Command::new("where").arg("cursor").output();

        #[cfg(not(target_os = "windows"))]
        let check_cmd = std::process::Command::new("which").arg("cursor").output();

        check_cmd
            .map(|output| output.status.success())
            .unwrap_or(false)
    }

    fn scan(&self, preset_files: &PresetFiles, _target_dir: &Path) -> ScanResult {
        let mut result = ScanResult::new();
        let cursorrules = self.cursorrules_file();
        let mcp_file = self.cursor_dir().join("mcp.json");

        // Rules → .cursorrules
        if !preset_files.rules.is_empty() {
            result.add_change(
                ".cursorrules".to_string(),
                "rules".to_string(),
                cursorrules.exists(),
            );
        }

        // Memory → .cursorrules (appended)
        if !preset_files.memory.is_empty() {
            result.add_change(
                ".cursorrules".to_string(),
                "memory".to_string(),
                cursorrules.exists(),
            );
        }

        // Commands
        for file in &preset_files.commands {
            let filename = file.relative_path.replace("commands/", "");
            let target = format!(".cursor/commands/{}", filename);
            let target_path = self.cursor_dir().join("commands").join(&filename);
            result.add_change_with_content(
                target,
                "commands".to_string(),
                &target_path,
                &file.content,
            );
        }

        // MCP
        if !preset_files.mcp.is_empty() {
            result.add_change(
                ".cursor/mcp.json".to_string(),
                "mcp".to_string(),
                mcp_file.exists(),
            );
        }

        // Hooks
        if !preset_files.hooks.is_empty() {
            let hooks_file = self.cursor_dir().join("hooks.json");
            result.add_change(
                ".cursor/hooks.json".to_string(),
                "hooks".to_string(),
                hooks_file.exists(),
            );
        }

        // Agents
        for file in &preset_files.agents {
            let filename = file.relative_path.replace("agents/", "");
            let target = format!(".cursor/agents/{}", filename);
            let target_path = self.cursor_dir().join("agents").join(&filename);
            result.add_change_with_content(
                target,
                "agents".to_string(),
                &target_path,
                &file.content,
            );
        }

        // Skills
        for file in &preset_files.skills {
            let filename = file.relative_path.replace("skills/", "");
            let target = format!(".cursor/skills/{}", filename);
            let target_path = self.cursor_dir().join("skills").join(&filename);
            result.add_change_with_content(
                target,
                "skills".to_string(),
                &target_path,
                &file.content,
            );
        }

        result
    }

    fn apply(
        &self,
        preset_files: &PresetFiles,
        _target_dir: &Path,
        conflict_mode: ConflictMode,
    ) -> Result<ApplyResult> {
        self.ensure_cursor_dir()?;

        let mut result = ApplyResult::new();
        let mut mode = conflict_mode;

        // Apply each section
        self.apply_rules(&preset_files.rules, &mut result, &mut mode)?;
        self.apply_memory(&preset_files.memory, &mut result, &mut mode)?;
        self.apply_commands(&preset_files.commands, &mut result, &mut mode)?;
        self.apply_mcp(&preset_files.mcp, &mut result, &mut mode)?;
        self.apply_hooks(&preset_files.hooks, &mut result, &mut mode)?;
        self.apply_agents(&preset_files.agents, &mut result, &mut mode)?;
        self.apply_skills(&preset_files.skills, &mut result, &mut mode)?;

        Ok(result)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn create_test_adapter() -> (TempDir, CursorAdapter) {
        let temp_dir = TempDir::new().unwrap();
        let adapter = CursorAdapter::new(temp_dir.path());
        (temp_dir, adapter)
    }

    #[test]
    fn test_adapter_name() {
        let (_temp_dir, adapter) = create_test_adapter();
        assert_eq!(adapter.name(), "Cursor");
    }

    #[test]
    fn test_detect_no_cursor() {
        let (temp_dir, _adapter) = create_test_adapter();
        // Verify no cursor files exist
        assert!(!temp_dir.path().join(".cursorrules").exists());
        assert!(!temp_dir.path().join(".cursor").exists());
    }

    #[test]
    fn test_detect_with_cursorrules() {
        let (temp_dir, adapter) = create_test_adapter();
        fs::write(temp_dir.path().join(".cursorrules"), "# Rules").unwrap();
        assert!(adapter.detect());
    }

    #[test]
    fn test_detect_with_cursor_dir() {
        let (temp_dir, adapter) = create_test_adapter();
        fs::create_dir_all(temp_dir.path().join(".cursor")).unwrap();
        assert!(adapter.detect());
    }

    #[test]
    fn test_apply_rules() {
        let (temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/code-style.md".to_string(),
                content: "# Code Style".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), ConflictMode::Force)
            .unwrap();

        assert!(!result.created.is_empty() || !result.updated.is_empty());

        let cursorrules = temp_dir.path().join(".cursorrules");
        assert!(cursorrules.exists());
        let content = fs::read_to_string(cursorrules).unwrap();
        assert!(content.contains("# Code Style"));
    }

    #[test]
    fn test_apply_rules_existing() {
        let (temp_dir, adapter) = create_test_adapter();

        // Create existing .cursorrules
        fs::write(temp_dir.path().join(".cursorrules"), "# Existing Rules").unwrap();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/new.md".to_string(),
                content: "# New Rules".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), ConflictMode::Force)
            .unwrap();

        // Should update existing file
        assert!(result.updated.iter().any(|f| f.contains(".cursorrules")));
    }

    #[test]
    fn test_apply_commands() {
        let (temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            commands: vec![PresetFile {
                relative_path: "commands/test.md".to_string(),
                content: "# Test Command".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), ConflictMode::Force)
            .unwrap();

        assert!(result.created.iter().any(|f| f.contains("test.md")));

        let cmd_file = temp_dir.path().join(".cursor/commands/test.md");
        assert!(cmd_file.exists());
    }

    #[test]
    fn test_scan() {
        let (_temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/test.md".to_string(),
                content: "# Test".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter.scan(&preset_files, Path::new("."));

        assert!(result.has_changes());
        assert!(!result.has_conflicts());
    }

    #[test]
    fn test_scan_conflicts() {
        let (temp_dir, adapter) = create_test_adapter();

        // Create existing file
        fs::write(temp_dir.path().join(".cursorrules"), "existing").unwrap();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/new.md".to_string(),
                content: "# New".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter.scan(&preset_files, temp_dir.path());

        assert!(result.has_conflicts());
    }
}
