use super::traits::{
    has_frontmatter, strip_section_prefix, write_with_conflict, ApplyResult, ConflictMode,
    PresetFile, PresetFiles, ScanResult, ToolAdapter,
};
use crate::error::Result;
use std::fs;
use std::path::{Path, PathBuf};

/// Cursor adapter
///
/// Converts presets to Cursor format:
/// - rules/*.md → .cursor/rules/*.md or *.mdc (frontmatter → .mdc, otherwise → .md)
/// - memory/*.md → .cursorrules (appended)
/// - commands/*.md → .cursor/commands/
/// - mcp/*.json → .cursor/mcp.json (mcpServers section)
/// - hooks/*.json → .cursor/hooks.json
/// - agents/*.md → .cursor/agents/
/// - skills/*.ts → .cursor/skills/
pub struct CursorAdapter {
    project_dir: PathBuf,
}

impl CursorAdapter {
    pub fn new(project_dir: &Path) -> Self {
        Self {
            project_dir: project_dir.to_path_buf(),
        }
    }

    /// Get the .cursor directory path
    fn cursor_dir(&self) -> PathBuf {
        self.project_dir.join(".cursor")
    }

    /// Get the .cursorrules file path
    fn cursorrules_file(&self) -> PathBuf {
        self.project_dir.join(".cursorrules")
    }

    /// Ensure .cursor directory exists
    fn ensure_cursor_dir(&self) -> Result<()> {
        let cursor_dir = self.cursor_dir();
        if !cursor_dir.exists() {
            fs::create_dir_all(&cursor_dir)?;
        }
        Ok(())
    }

    /// Determine the target filename for a rule file based on frontmatter presence.
    /// Files with YAML frontmatter get .mdc extension, others keep .md.
    fn rule_target_filename(relative_path: &str, content: &str) -> String {
        let filename = strip_section_prefix(relative_path, "rules");
        if has_frontmatter(content) {
            // If front matter exists, convert .md to .mdc
            if let Some(stem) = filename.strip_suffix(".md") {
                format!("{}.mdc", stem)
            } else {
                filename
            }
        } else {
            filename
        }
    }

    /// Apply rules files: rules/*.md → .cursor/rules/*.md or *.mdc
    fn apply_rules(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let rules_dir = self.cursor_dir().join("rules");
        fs::create_dir_all(&rules_dir)?;

        for file in files {
            let filename = Self::rule_target_filename(&file.relative_path, &file.content);
            let target_path = rules_dir.join(&filename);
            let display_path = format!(".cursor/rules/{}", filename);

            write_with_conflict(&target_path, &file.content, mode, result, &display_path)?;
        }

        Ok(())
    }

    /// Apply memory files: memory/*.md → .cursorrules (appended)
    fn apply_memory(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let cursorrules = self.cursorrules_file();

        // Build memory content
        let mut memory_content = String::from("\n\n---\n\n# Project Memory\n\n");
        for (i, file) in files.iter().enumerate() {
            if i > 0 {
                memory_content.push_str("\n\n---\n\n");
            }
            memory_content.push_str(&format!(
                "## {}\n\n",
                strip_section_prefix(&file.relative_path, "memory").replace(".md", "")
            ));
            memory_content.push_str(&file.content);
        }

        // Read existing content or create header
        let base = if cursorrules.exists() {
            fs::read_to_string(&cursorrules)?
        } else {
            String::from("# Cursor Rules\n# Generated by aidot\n")
        };
        let content = format!("{}{}", base, memory_content);

        write_with_conflict(&cursorrules, &content, mode, result, ".cursorrules")?;

        Ok(())
    }

    /// Apply commands: commands/*.md → .cursor/commands/
    fn apply_commands(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let commands_dir = self.cursor_dir().join("commands");
        fs::create_dir_all(&commands_dir)?;

        for file in files {
            let filename = strip_section_prefix(&file.relative_path, "commands");
            let target_path = commands_dir.join(&filename);
            let display_path = format!(".cursor/commands/{}", filename);

            write_with_conflict(&target_path, &file.content, mode, result, &display_path)?;
        }

        Ok(())
    }

    /// Apply MCP configs: mcp/*.json → .cursor/mcp.json (mcpServers section)
    fn apply_mcp(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let mcp_file = self.cursor_dir().join("mcp.json");

        // Read existing or create new
        let mut mcp_config: serde_json::Value = if mcp_file.exists() {
            let content = fs::read_to_string(&mcp_file)?;
            serde_json::from_str(&content)?
        } else {
            serde_json::json!({})
        };

        // Ensure mcpServers object exists
        if mcp_config.get("mcpServers").is_none() {
            mcp_config["mcpServers"] = serde_json::json!({});
        }

        // Merge MCP configurations
        for file in files {
            let server_config: serde_json::Value = serde_json::from_str(&file.content)?;
            let server_name = strip_section_prefix(&file.relative_path, "mcp").replace(".json", "");
            mcp_config["mcpServers"][server_name] = server_config;
        }

        let json_str = serde_json::to_string_pretty(&mcp_config)?;
        write_with_conflict(&mcp_file, &json_str, mode, result, ".cursor/mcp.json")?;

        Ok(())
    }

    /// Apply hooks: hooks/*.json → .cursor/hooks.json
    fn apply_hooks(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let hooks_file = self.cursor_dir().join("hooks.json");

        // Merge all hooks into one JSON object with standard structure
        let mut hooks_config = serde_json::json!({
            "version": 1,
            "hooks": {}
        });

        for file in files {
            let hook_config: serde_json::Value = serde_json::from_str(&file.content)?;
            let hook_name = strip_section_prefix(&file.relative_path, "hooks").replace(".json", "");

            // Add to hooks object
            if let Some(hooks_obj) = hooks_config.get_mut("hooks") {
                hooks_obj[hook_name] = hook_config;
            }
        }

        let json_str = serde_json::to_string_pretty(&hooks_config)?;
        write_with_conflict(&hooks_file, &json_str, mode, result, ".cursor/hooks.json")?;

        Ok(())
    }

    /// Apply agents: agents/*.md → .cursor/agents/
    fn apply_agents(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let agents_dir = self.cursor_dir().join("agents");
        fs::create_dir_all(&agents_dir)?;

        for file in files {
            let filename = strip_section_prefix(&file.relative_path, "agents");
            let target_path = agents_dir.join(&filename);
            let display_path = format!(".cursor/agents/{}", filename);

            write_with_conflict(&target_path, &file.content, mode, result, &display_path)?;
        }

        Ok(())
    }

    /// Apply skills: skills/*.ts → .cursor/skills/
    fn apply_skills(
        &self,
        files: &[PresetFile],
        result: &mut ApplyResult,
        mode: &mut ConflictMode,
    ) -> Result<()> {
        if files.is_empty() {
            return Ok(());
        }

        let skills_dir = self.cursor_dir().join("skills");
        fs::create_dir_all(&skills_dir)?;

        for file in files {
            let filename = strip_section_prefix(&file.relative_path, "skills");
            let target_path = skills_dir.join(&filename);
            let display_path = format!(".cursor/skills/{}", filename);

            write_with_conflict(&target_path, &file.content, mode, result, &display_path)?;
        }

        Ok(())
    }
}

impl ToolAdapter for CursorAdapter {
    fn name(&self) -> &str {
        "Cursor"
    }

    fn detect(&self) -> bool {
        // Check if .cursorrules file exists
        if self.cursorrules_file().exists() {
            return true;
        }

        // Check if .cursor directory exists
        if self.cursor_dir().exists() {
            return true;
        }

        // Check if cursor command exists
        #[cfg(target_os = "windows")]
        let check_cmd = std::process::Command::new("where").arg("cursor").output();

        #[cfg(not(target_os = "windows"))]
        let check_cmd = std::process::Command::new("which").arg("cursor").output();

        check_cmd
            .map(|output| output.status.success())
            .unwrap_or(false)
    }

    fn scan(&self, preset_files: &PresetFiles, _target_dir: &Path) -> ScanResult {
        let mut result = ScanResult::new();
        let cursorrules = self.cursorrules_file();
        let mcp_file = self.cursor_dir().join("mcp.json");

        // Rules → .cursor/rules/*.md or *.mdc
        for file in &preset_files.rules {
            let filename = CursorAdapter::rule_target_filename(&file.relative_path, &file.content);
            let target = format!(".cursor/rules/{}", filename);
            let target_path = self.cursor_dir().join("rules").join(&filename);
            result.add_change_with_content(
                target,
                "rules".to_string(),
                &target_path,
                &file.content,
            );
        }

        // Memory → .cursorrules (appended)
        if !preset_files.memory.is_empty() {
            result.add_change(
                ".cursorrules".to_string(),
                "memory".to_string(),
                cursorrules.exists(),
            );
        }

        // Commands
        for file in &preset_files.commands {
            let filename = strip_section_prefix(&file.relative_path, "commands");
            let target = format!(".cursor/commands/{}", filename);
            let target_path = self.cursor_dir().join("commands").join(&filename);
            result.add_change_with_content(
                target,
                "commands".to_string(),
                &target_path,
                &file.content,
            );
        }

        // MCP
        if !preset_files.mcp.is_empty() {
            result.add_change(
                ".cursor/mcp.json".to_string(),
                "mcp".to_string(),
                mcp_file.exists(),
            );
        }

        // Hooks
        if !preset_files.hooks.is_empty() {
            let hooks_file = self.cursor_dir().join("hooks.json");
            result.add_change(
                ".cursor/hooks.json".to_string(),
                "hooks".to_string(),
                hooks_file.exists(),
            );
        }

        // Agents
        for file in &preset_files.agents {
            let filename = strip_section_prefix(&file.relative_path, "agents");
            let target = format!(".cursor/agents/{}", filename);
            let target_path = self.cursor_dir().join("agents").join(&filename);
            result.add_change_with_content(
                target,
                "agents".to_string(),
                &target_path,
                &file.content,
            );
        }

        // Skills
        for file in &preset_files.skills {
            let filename = strip_section_prefix(&file.relative_path, "skills");
            let target = format!(".cursor/skills/{}", filename);
            let target_path = self.cursor_dir().join("skills").join(&filename);
            result.add_change_with_content(
                target,
                "skills".to_string(),
                &target_path,
                &file.content,
            );
        }

        result
    }

    fn apply(
        &self,
        preset_files: &PresetFiles,
        _target_dir: &Path,
        conflict_mode: &mut ConflictMode,
    ) -> Result<ApplyResult> {
        self.ensure_cursor_dir()?;

        let mut result = ApplyResult::new();

        // Apply merged sections first (may trigger interactive prompts)
        self.apply_memory(&preset_files.memory, &mut result, conflict_mode)?;
        self.apply_mcp(&preset_files.mcp, &mut result, conflict_mode)?;
        self.apply_hooks(&preset_files.hooks, &mut result, conflict_mode)?;
        // 1:1 mapped sections (resolved immediately from PreResolved map)
        self.apply_rules(&preset_files.rules, &mut result, conflict_mode)?;
        self.apply_commands(&preset_files.commands, &mut result, conflict_mode)?;
        self.apply_agents(&preset_files.agents, &mut result, conflict_mode)?;
        self.apply_skills(&preset_files.skills, &mut result, conflict_mode)?;

        Ok(result)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn create_test_adapter() -> (TempDir, CursorAdapter) {
        let temp_dir = TempDir::new().unwrap();
        let adapter = CursorAdapter::new(temp_dir.path());
        (temp_dir, adapter)
    }

    #[test]
    fn test_adapter_name() {
        let (_temp_dir, adapter) = create_test_adapter();
        assert_eq!(adapter.name(), "Cursor");
    }

    #[test]
    fn test_detect_no_cursor() {
        let (temp_dir, _adapter) = create_test_adapter();
        // Verify no cursor files exist
        assert!(!temp_dir.path().join(".cursorrules").exists());
        assert!(!temp_dir.path().join(".cursor").exists());
    }

    #[test]
    fn test_detect_with_cursorrules() {
        let (temp_dir, adapter) = create_test_adapter();
        fs::write(temp_dir.path().join(".cursorrules"), "# Rules").unwrap();
        assert!(adapter.detect());
    }

    #[test]
    fn test_detect_with_cursor_dir() {
        let (temp_dir, adapter) = create_test_adapter();
        fs::create_dir_all(temp_dir.path().join(".cursor")).unwrap();
        assert!(adapter.detect());
    }

    #[test]
    fn test_apply_rules_without_frontmatter() {
        let (temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/code-style.md".to_string(),
                content: "# Code Style".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), &mut ConflictMode::Force)
            .unwrap();

        assert!(!result.created.is_empty());

        // Without front matter, keep .md extension
        let rule_file = temp_dir.path().join(".cursor/rules/code-style.md");
        assert!(rule_file.exists());
        let content = fs::read_to_string(rule_file).unwrap();
        assert!(content.contains("# Code Style"));
    }

    #[test]
    fn test_apply_rules_with_frontmatter() {
        let (temp_dir, adapter) = create_test_adapter();

        let content_with_frontmatter =
            "---\ndescription: Code style rules\nglobs: \"**/*.rs\"\n---\n# Code Style".to_string();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/code-style.md".to_string(),
                content: content_with_frontmatter.clone(),
            }],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), &mut ConflictMode::Force)
            .unwrap();

        assert!(!result.created.is_empty());

        // With front matter, convert to .mdc extension
        let rule_file = temp_dir.path().join(".cursor/rules/code-style.mdc");
        assert!(rule_file.exists());
        let content = fs::read_to_string(rule_file).unwrap();
        assert!(content.contains("# Code Style"));
    }

    #[test]
    fn test_apply_rules_mixed_frontmatter() {
        let (temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            rules: vec![
                PresetFile {
                    relative_path: "rules/plain.md".to_string(),
                    content: "# Plain rule".to_string(),
                },
                PresetFile {
                    relative_path: "rules/with-meta.md".to_string(),
                    content: "---\ndescription: Meta rule\n---\n# Meta rule".to_string(),
                },
            ],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), &mut ConflictMode::Force)
            .unwrap();

        assert_eq!(result.created.len(), 2);

        // plain.md -> keep .md
        assert!(temp_dir.path().join(".cursor/rules/plain.md").exists());
        // with-meta.md -> convert to .mdc
        assert!(temp_dir.path().join(".cursor/rules/with-meta.mdc").exists());
    }

    #[test]
    fn test_apply_rules_existing() {
        let (temp_dir, adapter) = create_test_adapter();

        // Create existing file
        let rules_dir = temp_dir.path().join(".cursor/rules");
        fs::create_dir_all(&rules_dir).unwrap();
        fs::write(rules_dir.join("existing.md"), "# Old Rules").unwrap();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/existing.md".to_string(),
                content: "# New Rules".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), &mut ConflictMode::Force)
            .unwrap();

        assert!(result
            .updated
            .iter()
            .any(|f| f.contains(".cursor/rules/existing.md")));
    }

    #[test]
    fn test_apply_commands() {
        let (temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            commands: vec![PresetFile {
                relative_path: "commands/test.md".to_string(),
                content: "# Test Command".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter
            .apply(&preset_files, temp_dir.path(), &mut ConflictMode::Force)
            .unwrap();

        assert!(result.created.iter().any(|f| f.contains("test.md")));

        let cmd_file = temp_dir.path().join(".cursor/commands/test.md");
        assert!(cmd_file.exists());
    }

    #[test]
    fn test_scan() {
        let (_temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/test.md".to_string(),
                content: "# Test".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter.scan(&preset_files, Path::new("."));

        assert!(result.has_changes());
        assert!(!result.has_conflicts());
        // Verify scan results use .cursor/rules/ path
        assert!(result.changes[0].path.starts_with(".cursor/rules/"));
    }

    #[test]
    fn test_scan_with_frontmatter() {
        let (_temp_dir, adapter) = create_test_adapter();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/test.md".to_string(),
                content: "---\ndescription: test\n---\n# Test".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter.scan(&preset_files, Path::new("."));

        assert!(result.has_changes());
        // Has front matter, so .mdc extension
        assert_eq!(result.changes[0].path, ".cursor/rules/test.mdc");
    }

    #[test]
    fn test_scan_conflicts() {
        let (temp_dir, adapter) = create_test_adapter();

        // Create existing file in .cursor/rules/
        let rules_dir = temp_dir.path().join(".cursor/rules");
        fs::create_dir_all(&rules_dir).unwrap();
        fs::write(rules_dir.join("new.md"), "existing").unwrap();

        let preset_files = PresetFiles {
            rules: vec![PresetFile {
                relative_path: "rules/new.md".to_string(),
                content: "# New".to_string(),
            }],
            ..Default::default()
        };

        let result = adapter.scan(&preset_files, temp_dir.path());

        assert!(result.has_conflicts());
    }
}
